using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;

// ReSharper disable once CheckNamespace

namespace GameLovers.AssetLoader
{
	/// <summary>
	/// Represents a configuration of an Addressable with all it's important data
	/// The Id is the int representation of the AddressableId generated by the AddressableIdsGenerator code generator
	/// </summary>
	[Serializable]
	public struct AddressableConfig
	{
		public int Id;
		public string Address;
		public string Path;
		public string AssetFileType;
		public Type AssetType;
		public ReadOnlyCollection<string> Labels;
		
		public AddressableConfig(int id, string address, string path, Type assetType, string[] labels)
		{
			Id = id;
			Address = address;
			Path = path;
			AssetFileType = path.Substring(path.LastIndexOf('.') + 1);
			AssetType = assetType;
			Labels = new ReadOnlyCollection<string>(labels);
		}
	}

	/// <summary>
	/// Avoids boxing for Dictionary
	/// </summary>
	public class AddressableConfigComparer : IEqualityComparer<AddressableConfig>
	{
		/// <inheritdoc />
		public bool Equals(AddressableConfig x, AddressableConfig y)
		{
			return x.Id == y.Id;
		}

		/// <inheritdoc />
		public int GetHashCode(AddressableConfig config)
		{
			return config.Id;
		}
	}
}